apiVersion: apps/v1
kind: Deployment
metadata:
  name: ra-ds-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ra-ds-explorer
  template:
    metadata:
      labels:
        app: ra-ds-explorer
    spec:
      containers:
        - name: explorer
          image: ra-ds-explorer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: rads-config
