# =============================================================================
# TransportMode.CURL
# =============================================================================
def test_list_certificates(): ...
def test_get_certificate_by_serial(): ...
def test_list_users(): ...
def test_list_cert_requests(): ...
