class APIContractError(Exception): ...


class CertificateNotFound(Exception): ...


class CertificateServiceError(Exception): ...


class UnexpectedSchemaError(Exception): ...


class APIError(Exception): ...


class NotFound(APIError): ...


class ValidationError(APIError): ...
