class ApplicationError(Exception): ...


class APIError(ApplicationError): ...


class APIContractError(APIError): ...


class NotFound(APIError): ...


class ValidationError(APIError): ...


class CertificateNotFound(APIError): ...


class CertificateServiceError(APIError): ...
